#!/usr/bin/env bash
# A script that Displays a list of currently running processes
# shows all processes for all usersnIncluding those which might not have a TTY
# Display in a user oriented format
# Shows process hierarchy

ps -auxf
